all:
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_user: adminUsername
  hosts:
    13.80.102.159:
    20.73.57.209:
    20.71.32.135:
    20.67.101.18:
  children:
    nfs:
      hosts:
        13.80.102.159:
    master:
      hosts:
        20.73.57.209:
    workers:
      hosts:
        20.71.32.135:
        20.67.101.18:


